language: elixir
elixir:
  - 1.8.2
  - 1.9.1
otp_release:
  - 20.0
  - 21.0
  - 22.0
script:
  - mix format --check-formatted
  - MIX_ENV=test mix local.hex --force && MIX_ENV=test mix do deps.get, test
